name: locadeserta
description: Loca Deserta. The life of struggle.
version: 1.0.50-arm64
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
# version: 1.0.0+1useProguard

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  splashscreen:
  path_provider: ^0.5.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: 0.3.1 # add dependency for Firebase Core
  cloud_firestore: 0.9.7
  url_launcher: ^3.0.3
  firebase_auth: 0.8.3
  google_sign_in: 4.0.1+3
  shared_preferences: 0.5.1+2
  simple_animations: ^1.0.0
  swipedetector: 1.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - stories/LocaDeserta.json
    - stories/locadeserta.ink.json
    # bulrush images
    - images/background/bulrush/c_0.jpg
    - images/background/bulrush/0.jpg
    - images/background/bulrush/c_1.jpg
    - images/background/bulrush/1.jpg
    - images/background/bulrush/c_2.jpg
    - images/background/bulrush/2.jpg
    - images/background/bulrush/c_3.jpg
    - images/background/bulrush/3.jpg
    - images/background/bulrush/c_4.jpg
    - images/background/bulrush/4.jpg
    - images/background/bulrush/c_5.jpg
    - images/background/bulrush/5.jpg
    - images/background/bulrush/c_6.jpg
    - images/background/bulrush/6.jpg
    - images/background/bulrush/c_7.jpg
    - images/background/bulrush/7.jpg
    - images/background/bulrush/c_8.jpg
    - images/background/bulrush/8.jpg
    - images/background/bulrush/c_9.jpg
    - images/background/bulrush/9.jpg
    - images/background/bulrush/c_10.jpg
    - images/background/bulrush/10.jpg
    - images/background/bulrush/c_11.jpg
    - images/background/bulrush/11.jpg
    # BOAT IMAGES
    - images/background/boat/0.jpg
    - images/background/boat/1.jpg
    - images/background/boat/2.jpg
    - images/background/boat/3.jpg
    - images/background/boat/4.jpg
    - images/background/boat/5.jpg
    - images/background/boat/6.jpg
    - images/background/boat/7.jpg
    - images/background/boat/8.jpg
    - images/background/boat/9.jpg
    - images/background/boat/10.jpg
    - images/background/boat/11.jpg
    - images/background/boat/12.jpg
    - images/background/boat/13.jpg
    - images/background/boat/14.jpg
    - images/background/boat/c_0.jpg
    - images/background/boat/c_1.jpg
    - images/background/boat/c_2.jpg
    - images/background/boat/c_3.jpg
    - images/background/boat/c_4.jpg
    - images/background/boat/c_5.jpg
    - images/background/boat/c_6.jpg
    - images/background/boat/c_7.jpg
    - images/background/boat/c_8.jpg
    - images/background/boat/c_9.jpg
    - images/background/boat/c_10.jpg
    - images/background/boat/c_11.jpg
    - images/background/boat/c_12.jpg
    - images/background/boat/c_13.jpg
    - images/background/boat/c_14.jpg
    # FOREST IMAGES
    - images/background/forest/0.jpg
    - images/background/forest/1.jpg
    - images/background/forest/2.jpg
    - images/background/forest/3.jpg
    - images/background/forest/4.jpg
    - images/background/forest/5.jpg
    - images/background/forest/6.jpg
    - images/background/forest/7.jpg
    - images/background/forest/8.jpg
    - images/background/forest/9.jpg
    - images/background/forest/c_0.jpg
    - images/background/forest/c_1.jpg
    - images/background/forest/c_2.jpg
    - images/background/forest/c_3.jpg
    - images/background/forest/c_4.jpg
    - images/background/forest/c_5.jpg
    - images/background/forest/c_6.jpg
    - images/background/forest/c_7.jpg
    - images/background/forest/c_8.jpg
    - images/background/forest/c_9.jpg
    # RIVER IMAGES
    - images/background/river/0.jpg
    - images/background/river/1.jpg
    - images/background/river/2.jpg
    - images/background/river/3.jpg
    - images/background/river/4.jpg
    - images/background/river/5.jpg
    - images/background/river/6.jpg
    - images/background/river/7.jpg
    - images/background/river/8.jpg
    - images/background/river/9.jpg
    - images/background/river/10.jpg
    - images/background/river/11.jpg
    - images/background/river/12.jpg
    - images/background/river/13.jpg
    - images/background/river/14.jpg
    - images/background/river/c_0.jpg
    - images/background/river/c_1.jpg
    - images/background/river/c_2.jpg
    - images/background/river/c_3.jpg
    - images/background/river/c_4.jpg
    - images/background/river/c_5.jpg
    - images/background/river/c_6.jpg
    - images/background/river/c_7.jpg
    - images/background/river/c_8.jpg
    - images/background/river/c_9.jpg
    - images/background/river/c_10.jpg
    - images/background/river/c_11.jpg
    - images/background/river/c_12.jpg
    - images/background/river/c_13.jpg
    - images/background/river/c_14.jpg
    - images/background/cossack_0.jpg
    - images/background/c_cossack_0.jpg
    - images/background/landing/0.jpg
    - images/background/landing/1.jpg
    - images/background/landing/c_0.jpg
    - images/background/landing/c_1.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto/Roboto-Bold.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
    - family: Raleway-Bold
      fonts:
        - asset: fonts/Raleway/Raleway-Bold.ttf
    - family: Raleway-Black
      fonts:
        - asset: fonts/Raleway/Raleway-Black.ttf