name: locadeserta
description: Loca Deserta. The life of struggle.
version: 1.0.14
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
# version: 1.0.0+1useProguard

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^0.5.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: 0.3.1 # add dependency for Firebase Core
  cloud_firestore: 0.9.7
  url_launcher: ^3.0.3
  firebase_auth: 0.8.3
  google_sign_in: 4.0.1+3
  shared_preferences: 0.5.1+2
  simple_animations: ^1.0.0
  swipedetector: 1.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - stories/LocaDeserta.json
    - stories/locadeserta.ink.json
    - images/background/boat_0.jpg
    - images/background/boat_1.jpg
    - images/background/boat_2.jpg
    - images/background/boat_3.jpg
    - images/background/boat_4.jpg
    - images/background/boat_5.jpg
    - images/background/boat_6.jpg
    - images/background/boat_7.jpg
    - images/background/boat_8.jpg
    - images/background/boat_9.jpg
    - images/background/boat_10.jpg
    - images/background/boat_11.jpg
    - images/background/boat_12.jpg
    - images/background/boat_13.jpg
    - images/background/boat_14.jpg
    - images/landing/landing_0.jpg
    - images/landing/landing_1.jpg
    - images/landing/landing_2.jpg
    - images/landing/landing_3.jpg
#    - images/background/cossack_0.jpg
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto/Roboto-Bold.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
    - family: Raleway-Bold
      fonts:
        - asset: fonts/Raleway/Raleway-Bold.ttf
    - family: Raleway-Black
      fonts:
        - asset: fonts/Raleway/Raleway-Black.ttf