name: server
description: A simple server to upload and publish markdown version of stories


environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angel_cors: ^2.0.0
  nanoid: ^0.1.0
  gladstoriesengine:
    path:
      ../../gladstoriesdart

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  angel_framework: ^2.0.0
