name: sloboda
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6
  url_launcher: 5.4.1
  cupertino_icons: ^0.1.2
  fluri: ^1.2.8
  clay_containers: ^0.2.2
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4

flutter:
  uses-material-design: true
  assets:
    # resource buildings
    - images/resource_buildings/iron_mine.png
    - images/resource_buildings/field.png
    - images/resource_buildings/quarry.png
    - images/resource_buildings/forest.png
    - images/resource_buildings/river.png
    - images/resource_buildings/trappershouse.png
    - images/resource_buildings/stable.png
    - images/resource_buildings/mill.png
    - images/resource_buildings/powder_cellar.png
    - images/resource_buildings/smith.png
    - images/resource_buildings/iron_mine_64.png
    - images/resource_buildings/field_64.png
    - images/resource_buildings/quarry_64.png
    - images/resource_buildings/forest_64.png
    - images/resource_buildings/river_64.png
    - images/resource_buildings/trappershouse_64.png
    - images/resource_buildings/stable_64.png
    - images/resource_buildings/mill_64.png
    - images/resource_buildings/powder_cellar_64.png
    - images/resource_buildings/smith_64.png
    # resources
    - images/resources/stone.png
    - images/resources/wood.png
    - images/resources/powder.png
    - images/resources/food.png
    - images/resources/money.png
    - images/resources/fur.png
    - images/resources/iron_ore.png
    - images/resources/fish.png
    - images/resources/horse.png
    - images/resources/firearm.png
    - images/resources/stone_64.png
    - images/resources/wood_64.png
    - images/resources/powder_64.png
    - images/resources/food_64.png
    - images/resources/money_64.png
    - images/resources/fur_64.png
    - images/resources/iron_ore_64.png
    - images/resources/fish_64.png
    - images/resources/horse_64.png
    - images/resources/firearm_64.png
    # city buildings
    - images/city_buildings/citizen.png
    - images/city_buildings/kurin.png
    - images/city_buildings/wall.png
    - images/city_buildings/watch_tower.png
    - images/city_buildings/church.png
    - images/city_buildings/tower.png
    - images/city_buildings/shooting_range.png
    - images/city_buildings/citizen_64.png
    - images/city_buildings/kurin_64.png
    - images/city_buildings/wall_64.png
    - images/city_buildings/watch_tower_64.png
    - images/city_buildings/church_64.png
    - images/city_buildings/tower_64.png
    - images/city_buildings/shooting_range_64.png
    # city props
    - images/city_props/glory.png
    - images/city_props/glory_64.png
    - images/city_props/defense.png
    - images/city_props/defense_64.png
    - images/city_props/faith.png
    - images/city_props/faith_64.png
    - images/city_props/citizen.png
    - images/city_props/citizen_64.png
    - images/city_props/cossack.png
    - images/city_props/cossack_64.png
    # UI part
    - images/ui/arrow_right.png

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto/Roboto-Bold.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
    - family: Raleway-Bold
      fonts:
        - asset: fonts/Raleway/Raleway-Bold.ttf
    - family: Raleway-Black
      fonts:
        - asset: fonts/Raleway/Raleway-Black.ttf
