name: locadeserta
description: Loca Deserta. Interactive Stories
version: 1.0.123
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  rxdart: ^0.26.0
  cupertino_icons: ^1.0.1+1
  url_launcher: ^6.0.2
  simple_animations: ^3.0.0
  pdf: ^3.0.1
  share: ^2.0.0
  tuple: ^2.0.0-nullsafety.0
  http: ^0.13.0
  gladstoriesengine: ^0.3.1
  shared_preferences: ^2.0.3
  flutter_markdown: ^0.6.0
  flutter_simple_treeview: ^3.0.0-nullsafety.1
  # graphview: ^0.6.1

dev_dependencies:
  flutter_launcher_icons: "^0.9.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher.png"

  # For information on the generic Dart part of this file, see the
  # following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #
    - images/other/
    # stories
    - assets/story_catalog.json
    - assets/stories/
    # bulrush images
    - images/background/bulrush/c_0.jpg
    - images/background/bulrush/0.jpg
    - images/background/bulrush/c_1.jpg
    - images/background/bulrush/1.jpg
    - images/background/bulrush/c_2.jpg
    - images/background/bulrush/2.jpg
    - images/background/bulrush/c_3.jpg
    - images/background/bulrush/3.jpg
    - images/background/bulrush/c_4.jpg
    - images/background/bulrush/4.jpg
    - images/background/bulrush/c_5.jpg
    - images/background/bulrush/5.jpg
    - images/background/bulrush/c_6.jpg
    - images/background/bulrush/6.jpg
    - images/background/bulrush/c_7.jpg
    - images/background/bulrush/7.jpg
    - images/background/bulrush/c_8.jpg
    - images/background/bulrush/8.jpg
    - images/background/bulrush/c_9.jpg
    - images/background/bulrush/9.jpg
    - images/background/bulrush/c_10.jpg
    - images/background/bulrush/10.jpg
    - images/background/bulrush/c_11.jpg
    - images/background/bulrush/11.jpg
    # BOAT IMAGES
    - images/background/boat/0.jpg
    - images/background/boat/1.jpg
    - images/background/boat/2.jpg
    - images/background/boat/3.jpg
    - images/background/boat/4.jpg
    - images/background/boat/5.jpg
    - images/background/boat/6.jpg
    - images/background/boat/7.jpg
    - images/background/boat/8.jpg
    - images/background/boat/9.jpg
    - images/background/boat/10.jpg
    - images/background/boat/11.jpg
    - images/background/boat/12.jpg
    - images/background/boat/13.jpg
    - images/background/boat/14.jpg
    - images/background/boat/15.jpg
    - images/background/boat/16.jpg
    - images/background/boat/17.jpg
    - images/background/boat/18.jpg
    - images/background/boat/c_0.jpg
    - images/background/boat/c_1.jpg
    - images/background/boat/c_2.jpg
    - images/background/boat/c_3.jpg
    - images/background/boat/c_4.jpg
    - images/background/boat/c_5.jpg
    - images/background/boat/c_6.jpg
    - images/background/boat/c_7.jpg
    - images/background/boat/c_8.jpg
    - images/background/boat/c_9.jpg
    - images/background/boat/c_10.jpg
    - images/background/boat/c_11.jpg
    - images/background/boat/c_12.jpg
    - images/background/boat/c_13.jpg
    - images/background/boat/c_14.jpg
    - images/background/boat/c_15.jpg
    - images/background/boat/c_16.jpg
    - images/background/boat/c_17.jpg
    - images/background/boat/c_18.jpg

    # FOREST IMAGES
    - images/background/forest/0.jpg
    - images/background/forest/1.jpg
    - images/background/forest/2.jpg
    - images/background/forest/3.jpg
    - images/background/forest/4.jpg
    - images/background/forest/5.jpg
    - images/background/forest/6.jpg
    - images/background/forest/7.jpg
    - images/background/forest/8.jpg
    - images/background/forest/9.jpg
    - images/background/forest/c_0.jpg
    - images/background/forest/c_1.jpg
    - images/background/forest/c_2.jpg
    - images/background/forest/c_3.jpg
    - images/background/forest/c_4.jpg
    - images/background/forest/c_5.jpg
    - images/background/forest/c_6.jpg
    - images/background/forest/c_7.jpg
    - images/background/forest/c_8.jpg
    - images/background/forest/c_9.jpg
    # RIVER IMAGES
    - images/background/river/0.jpg
    - images/background/river/1.jpg
    - images/background/river/2.jpg
    - images/background/river/3.jpg
    - images/background/river/4.jpg
    - images/background/river/5.jpg
    - images/background/river/6.jpg
    - images/background/river/7.jpg
    - images/background/river/8.jpg
    - images/background/river/9.jpg
    - images/background/river/10.jpg
    - images/background/river/11.jpg
    - images/background/river/12.jpg
    - images/background/river/13.jpg
    - images/background/river/14.jpg
    - images/background/river/15.jpg
    - images/background/river/16.jpg
    - images/background/river/17.jpg
    - images/background/river/18.jpg
    - images/background/river/19.jpg
    - images/background/river/20.jpg
    - images/background/river/21.jpg
    - images/background/river/c_0.jpg
    - images/background/river/c_1.jpg
    - images/background/river/c_2.jpg
    - images/background/river/c_3.jpg
    - images/background/river/c_4.jpg
    - images/background/river/c_5.jpg
    - images/background/river/c_6.jpg
    - images/background/river/c_7.jpg
    - images/background/river/c_8.jpg
    - images/background/river/c_9.jpg
    - images/background/river/c_10.jpg
    - images/background/river/c_11.jpg
    - images/background/river/c_12.jpg
    - images/background/river/c_13.jpg
    - images/background/river/c_14.jpg
    - images/background/river/c_15.jpg
    - images/background/river/c_16.jpg
    - images/background/river/c_17.jpg
    - images/background/river/c_18.jpg
    - images/background/river/c_19.jpg
    - images/background/river/c_20.jpg
    - images/background/river/c_21.jpg
    - images/background/cossack_0.jpg
    - images/background/c_cossack_0.jpg
    # LANDING IMAGES
    - images/background/landing/0.jpg
    - images/background/landing/1.jpg
    - images/background/landing/2.jpg
    - images/background/landing/3.jpg
    - images/background/landing/4.jpg
    - images/background/landing/5.jpg
    - images/background/landing/6.jpg
    - images/background/landing/7.jpg
    - images/background/landing/c_0.jpg
    - images/background/landing/c_1.jpg
    - images/background/landing/c_2.jpg
    - images/background/landing/c_3.jpg
    - images/background/landing/c_4.jpg
    - images/background/landing/c_5.jpg
    - images/background/landing/c_6.jpg
    - images/background/landing/c_7.jpg
    # CAMP IMAGES
    - images/background/camp/0.jpg
    - images/background/camp/1.jpg
    - images/background/camp/2.jpg
    - images/background/camp/3.jpg
    - images/background/camp/4.jpg
    - images/background/camp/5.jpg
    - images/background/camp/6.jpg
    - images/background/camp/7.jpg
    - images/background/camp/8.jpg
    - images/background/camp/9.jpg
    - images/background/camp/10.jpg
    - images/background/camp/11.jpg
    - images/background/camp/12.jpg
    - images/background/camp/13.jpg
    - images/background/camp/14.jpg
    - images/background/camp/c_0.jpg
    - images/background/camp/c_1.jpg
    - images/background/camp/c_2.jpg
    - images/background/camp/c_3.jpg
    - images/background/camp/c_4.jpg
    - images/background/camp/c_5.jpg
    - images/background/camp/c_6.jpg
    - images/background/camp/c_7.jpg
    - images/background/camp/c_8.jpg
    - images/background/camp/c_9.jpg
    - images/background/camp/c_10.jpg
    - images/background/camp/c_11.jpg
    - images/background/camp/c_12.jpg
    - images/background/camp/c_13.jpg
    - images/background/camp/c_14.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
    - family: Roboto-Bold
      fonts:
        - asset: fonts/Roboto/Roboto-Bold.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/Raleway-Regular.ttf
    - family: Raleway-Bold
      fonts:
        - asset: fonts/Raleway/Raleway-Bold.ttf
    - family: Raleway-Black
      fonts:
        - asset: fonts/Raleway/Raleway-Black.ttf