// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


function userExists(id) {
  return "SELECT COUNT(*) as count FROM users WHERE id = '" + (id + "'");
}

exports.userExists = userExists;
/* No side effect */
